- id: '1696836228866'                                                                                                                                                                  
  alias: Update Volume Minute            
  description: ''                        
  trigger:                               
  - platform: time_pattern               
    minutes: /1                          
  condition: []                          
  action:                                
  - service: script.check_for_data_update
    data: {}                          
  mode: single                        
- id: '1696865981799'                 
  alias: Reset Daily Values           
  description: ''                     
  trigger:                            
  - platform: time                    
    at: 00:00:00                      
  condition: []                       
  action:                                                             
  - service: counter.reset                                            
    data: {}                                                          
    target:                                                           
      entity_id: counter.event_counter                                
  - service: mqtt.publish                                             
    data:                                                             
      qos: 0                                                          
      topic: SMARTCUP/dailyVolume                                     
      payload: '0'                                                    
      retain: true                                                    
  mode: single                                                        
- id: '1696866034606'                                                 
  alias: Increment Counter                                            
  description: ''                                                     
  trigger:                                                            
  - platform: mqtt                                                    
    topic: SMARTCUP/volume                                            
  condition:                                                          
  - condition: template                                                                
    value_template: '{{ states(''sensor.cup_volume'') | float > 0 }}'                 
  action:                                                                              
  - service: counter.increment
    data: {}                             
    target:                              
      entity_id: counter.event_counter   
  - service: mqtt.publish                
    data:                                
      qos: 0                             
      topic: SMARTCUP/dailyVolume        
      payload: '0'                       
      retain: true                       
  mode: single                        
- id: '1696866034606'                 
  alias: Increment Counter            
  description: ''                     
  trigger:                            
  - platform: mqtt                    
    topic: SMARTCUP/volume            
  condition:                          
  - condition: template               
    value_template: '{{ states(''sensor.cup_volume'') | float > 0 }}'
  action:                                                            
  - service: counter.increment                                       
    data: {}                                                         
    target:                                                          
      entity_id: counter.event_counter                               
  - service: notify.mobile_app_juanchito                             
    data:                                                            
      message: Event detected                                        
  mode: single                                                       
- id: '1697004531098'                                                
  alias: Update Daily Volume                                         
  description: ''                                                    
  trigger:                                                           
  - platform: mqtt                                                   
    topic: SMARTCUP/volume                                           
  condition: []                                                      
  action:                                                            
  - variables:                                                       
      vol: '{{ states(''sensor.cup_volume'') | float  + states(''sensor.cup_daylvol'')
        | float }}'                                                                   
  - service: mqtt.publish                                                             
    data:                                                                             
      qos: 0                                                                          
      retain: true                                                                    
      topic: SMARTCUP/dailyVolume                                                     
      payload_template: '{{ vol }}'                                                   
  mode: single